version: 2.1

orbs:
  codecov: codecov/codecov@3.2.5

jobs:
  java-base-test:
    docker:
      - image: cimg/openjdk:20.0.1
    steps:
      - checkout
      - run: ./gradlew jacocoTestReport
      - codecov/upload:
          xtra_args: "--nonZero"

workflows:
  simple:
    jobs:
      - java-base-test