name: 'Meeko checks'

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test-platform:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    uses: ./.github/workflows/test.yml
    with:
      platform: ${{ matrix.os }}


  upload-codecov:
    needs:
      - test-platform
    uses: ./.github/workflows/upload-codcov.yml
