name: 'Test platform'

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: 'Setup Java'
        uses: ./.github/actions/setup-java

      - name: 'Run Gradle test'
        run: ./gradlew test
